version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: authentication-service-api:0.0.1-dev
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: test
      SWAGGER_ENABLED: true
